src/pegasus/apps/humanresources/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

from .views import (PersonalList, PersonalEdit, PersonalAdd, MarcacionList, PlanillaList,
                    PlanillaDetail, PlanillaAddView, PlanillaTrabDetail, PlanillaModalAddView,OrdenList,RequerimientoList )


admin.autodiscover()

urlpatterns = patterns(
    '',
    # Personal

    url(r'^personal$', PersonalList.as_view(), name='personal_list'),
    url(r'^personal/crear$', PersonalAdd.as_view(), name='personal_add'),
    url(r'^personal/(?P<pk>[0-9]{8})/editar$', PersonalEdit.as_view(), name='personal_edit'),


    # Planillas

    url(r'^(?P<current_year>[0-9]{4})/planillas$', PlanillaList.as_view(), name='planilla_list'),
    url(r'^(?P<current_year>[0-9]{4})/planilla/add$', PlanillaAddView.as_view(), name='planilla_add'),
    url(r'^planilla/modal/add$', PlanillaModalAddView.as_view(), name='planilla_modal_add'),
    url(r'^(?P<current_year>[0-9]{4})/planilla/(?P<pk>[0-9]+)/ver$', PlanillaDetail.as_view(), name='planilla_detail'),
    url(r'^(?P<current_year>[0-9]{4})/planilla_trab/(?P<pk>[0-9]+)/ver$', PlanillaTrabDetail.as_view(), name='planilla_trab_detail'),


    # Marcaciones

    url(r'^(?P<current_year>[0-9]{4})/marcaciones$', MarcacionList.as_view(), name='marcaciones_list'),



    #Ordenes de compra y servicio

    # url(r'^orden$', OrdenList.as_view(), name='orden_list'),
    url(r'^(?P<current_year>[0-9]{4})/orden$', OrdenList.as_view(), name='orden_list'),


    #Requerimiento de bienes y servicios

    # url(r'^orden$', OrdenList.as_view(), name='orden_list'),
    url(r'^(?P<current_year>[0-9]{4})/requerimiento$', RequerimientoList.as_view(), name='requerimiento_list'),




)

src/pegasus/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from pegasus.apps.humanresources.views import DashboardView


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^rrhh/', include('pegasus.apps.humanresources.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

src/pegasus/apps/humanresources/models.py
# coding=utf-8

from datetime import datetime

from dateutil.relativedelta import relativedelta
from django.db import models

from . import constants


class OrdenDetalle(models.Model):
    ano_eje = models.CharField(primary_key=True,max_length=4)
    n_orden = models.IntegerField()
    tipo = models.CharField(max_length=15)
    item = models.IntegerField()
    num_doc = models.CharField(max_length=15)
    especifica = models.CharField(max_length=16, blank=True)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    saldo = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    factor = models.IntegerField(blank=True, null=True)
    salida = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    id_item = models.CharField(max_length=13, blank=True)
    unidad = models.CharField(max_length=4, blank=True)
    desc_insumo = models.CharField(max_length=7000, blank=True)
    desc_calidad = models.CharField(max_length=1000, blank=True)
    precio_adj = models.DecimalField(max_digits=14, decimal_places=6, blank=True, null=True)
    cant_ing = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    temporal = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    unidad_alm = models.CharField(max_length=10, blank=True)
    class Meta:
        managed = False
        db_table = 'Orden_detalle'

class Orden(models.Model):
    ano_eje = models.CharField(primary_key=True, max_length=4)
    n_orden = models.ForeignKey(OrdenDetalle, db_column='n_orden')
    tipo = models.CharField(max_length=1)
    cod_doc = models.CharField(max_length=3)
    num_doc = models.CharField(max_length=15)
    fecha = models.DateTimeField()
    sec_func = models.CharField(max_length=4)
    fuente_financ = models.CharField(max_length=2)
    ruc_prov = models.CharField(db_column='RUC_prov', max_length=11) # Field name made lowercase.
    condiciones = models.CharField(max_length=1000, blank=True)
    ruc_fact = models.CharField(db_column='RUC_fact', max_length=11, blank=True) # Field name made lowercase.
    total = models.DecimalField(db_column='TOTAL', max_digits=10, decimal_places=2, blank=True, null=True) # Field name made lowercase.
    justificacion = models.CharField(max_length=400, blank=True)
    estado = models.CharField(max_length=1, blank=True)
    est_cont = models.CharField(max_length=1, blank=True)
    n_reg_siaf = models.IntegerField(blank=True, null=True)
    observaciones = models.CharField(max_length=100, blank=True)
    fech_comp = models.DateTimeField(blank=True, null=True)
    referencia = models.CharField(max_length=50, blank=True)
    ano_requer = models.CharField(max_length=4, blank=True)
    fecha_anul = models.DateTimeField(blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'Orden'


class RequerDetalle(models.Model):
    ano_eje = models.CharField(max_length=4)
    clasifica = models.CharField(max_length=1)
    n_requer = models.IntegerField()
    item = models.IntegerField()
    cantidad = models.DecimalField(max_digits=12, decimal_places=2)
    id_item = models.CharField(max_length=13)
    precio_ref = models.DecimalField(max_digits=14, decimal_places=3, blank=True, null=True)
    detalle = models.CharField(max_length=7000, blank=True)
    id_unidad = models.IntegerField(blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'Requer_detalle'

class Requerimiento(models.Model):
    ano_eje = models.CharField(primary_key=True, max_length=4)
    clasifica = models.CharField(max_length=1)
    # n_requer = models.IntegerField()
    n_requer = models.ForeignKey(RequerDetalle, db_column='n_requer')
    fecha = models.DateTimeField()
    mes = models.IntegerField()
    sec_func = models.CharField(max_length=4, blank=True)
    act_proy = models.CharField(max_length=7, blank=True)
    componente = models.CharField(max_length=7, blank=True)
    fuente_financ = models.CharField(max_length=2, blank=True)
    descripcion = models.CharField(max_length=1000, blank=True)
    condiciones = models.CharField(max_length=1000, blank=True)
    total = models.DecimalField(db_column='TOTAL', max_digits=12, decimal_places=2, blank=True, null=True) # Field name made lowercase.
    estado = models.CharField(max_length=1, blank=True)
    dni = models.CharField(db_column='DNI', max_length=8, blank=True) # Field name made lowercase.
    id_cargo = models.IntegerField(db_column='ID_cargo', blank=True, null=True) # Field name made lowercase.
    insitu = models.IntegerField(blank=True, null=True)
    arch_bases = models.CharField(max_length=200, blank=True)
    grupo = models.CharField(max_length=2, blank=True)
    clase = models.CharField(max_length=2, blank=True)
    proc_seleccion = models.CharField(max_length=10, blank=True)
    igv = models.IntegerField(blank=True, null=True)
    observacion = models.CharField(max_length=200, blank=True)
    selec = models.CharField(max_length=1, blank=True)
    paac = models.IntegerField(blank=True, null=True)
    fecha_autoriza = models.DateTimeField(blank=True, null=True)
    tipo_proc = models.CharField(max_length=3, blank=True)
    n_proc = models.IntegerField(blank=True, null=True)
    est_seace = models.CharField(max_length=1, blank=True)
    fecha_base = models.DateTimeField(blank=True, null=True)
    contrato = models.IntegerField(blank=True, null=True)
    fecha_contrato = models.DateTimeField(blank=True, null=True)
    fecha_fin_contrato = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Requerimiento'


class Mes(models.Model):
    mes_eje = models.CharField(primary_key=True, max_length=2)
    n_mes = models.IntegerField(blank=True, null=True)
    nombre = models.CharField(max_length=50)
    estado = models.CharField(max_length=1, blank=True)

    class Meta:
        managed = False
        db_table = 'mes'

    def __unicode__(self):
        return self.nombre


class ModalidadLaboral(models.Model):
    mod_laboral = models.CharField(primary_key=True, max_length=1)
    nombre = models.CharField(max_length=30, blank=True)
    abrev = models.CharField(max_length=15, blank=True)
    tipo_trab = models.CharField(max_length=2, blank=True)

    class Meta:
        managed = False
        db_table = 'modalidad_laboral'

    def __unicode__(self):
        return self.nombre


class Entidad(models.Model):
    codinst = models.CharField(primary_key=True, max_length=10)
    entidad = models.CharField(max_length=100)
    siglas = models.CharField(max_length=12)

    class Meta:
        managed = False
        db_table = 'entidad'


class Sectores(models.Model):
    cod_sect = models.CharField(primary_key=True, max_length=2)
    nombres = models.CharField(max_length=100)
    abrev = models.CharField(max_length=30)
    estado = models.CharField(max_length=1, blank=True)

    class Meta:
        managed = False
        db_table = 'sectores'

    def __unicode__(self):
        return self.nombres


class Personal(models.Model):
    dni = models.CharField(db_column='DNI', max_length=8, primary_key=True)  # Field name made lowercase.
    ap_paterno = models.CharField(max_length=40, blank=True)
    ap_materno = models.CharField(max_length=40, blank=True)
    nombres = models.CharField(max_length=50, blank=True)
    nomb_comp = models.CharField(max_length=120, blank=True)
    fecha_nac = models.DateTimeField(blank=True, null=True)
    sexo = models.CharField(max_length=1, blank=True, choices=constants.SEXO_CHOICES)
    # nacionalidad = models.ForeignKey(Pais, db_column='nacionalidad', blank=True, null=True)
    entidad = models.ForeignKey(Sectores, db_column='Entidad', blank=True)  # Field name made lowercase.
    telefono = models.CharField(max_length=20, blank=True)
    correo_e = models.CharField(max_length=50, blank=True)
    essalud_vida = models.CharField(max_length=1, blank=True)
    domicilio = models.CharField(max_length=150, blank=True)
    estado_civil = models.CharField(max_length=1, blank=True)
    nombre_pareja = models.CharField(max_length=120, blank=True)
    num_hijos = models.IntegerField(blank=True, null=True)
    ubica_foto = models.CharField(max_length=255, blank=True)
    ruc = models.CharField(db_column='RUC', max_length=11, blank=True)  # Field name made lowercase.
    retencion = models.CharField(max_length=1, blank=True)
    # tipo_trab = models.ForeignKey('TipoTrabajador', db_column='tipo_trab', blank=True, null=True)
    # nivel_educativo = models.ForeignKey(NivelEducativo, db_column='nivel_educativo', blank=True, null=True)
    # ocupacion = models.ForeignKey(Ocupacion, db_column='ocupacion', blank=True, null=True)
    discapacidad = models.CharField(max_length=1, blank=True)
    # reg_pension = models.ForeignKey('RegimenPensionario', db_column='reg_pension', blank=True, null=True)
    fecha_inscrip = models.DateTimeField(blank=True, null=True)
    cuspp = models.CharField(db_column='CUSPP', max_length=12, blank=True)  # Field name made lowercase.
    sctr_salud = models.CharField(db_column='SCTR_salud', max_length=1, blank=True)  # Field name made lowercase.
    sctr_pension = models.CharField(db_column='SCTR_pension', max_length=1, blank=True)  # Field name made lowercase.
    # tipo_contrato = models.ForeignKey('TipoContrato', db_column='tipo_contrato', blank=True, null=True)
    hor_nocturno = models.CharField(max_length=1, blank=True)
    sindicalizado = models.CharField(max_length=1, blank=True)
    desc_judicial = models.CharField(max_length=1, blank=True)
    periodicidad = models.CharField(max_length=1, blank=True)
    situacion = models.CharField(max_length=2, blank=True, choices=constants.SITUACION_CHOICES)

src/pegasus/apps/humanresources/forms.py
from django import forms

from .models import Planilla, ModalidadLaboral, Sectores, Mes, TipoPlanilla, Meta


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False,
                            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombres o DNI'}))


class PlanillaForm(forms.ModelForm):
    class Meta:
        model = Planilla
        fields = ['mes', 'tipo_planilla', 'mod_laboral', 'fuente_financ', 'sec_func', 'entidad']


class PlanillaPersonalForm(forms.Form):
    mod_laboral = forms.ModelChoiceField(ModalidadLaboral.objects)
    entidad = forms.ModelChoiceField(Sectores.objects)
    mes = forms.ModelChoiceField(Mes.objects)
    tipo_planilla = forms.ModelChoiceField(TipoPlanilla.objects)
    sec_func = forms.ModelChoiceField(Meta.objects)
    fuente_financ = forms.CharField()

    def __init__(self, ano_eje='2014', *args, **kwargs):
        super(PlanillaPersonalForm, self).__init__(*args, **kwargs)
        self.fields['sec_func'].queryset = Meta.objects.filter(ano_eje=ano_eje)

src/pegasus/apps/humanresources/views.py
# coding=utf-8
from django.views.generic import UpdateView, DetailView, CreateView, TemplateView
from django_genericfilters.views import FilteredListView

from .models import Personal, Marcacion, Planilla, PlanillaTrab,Orden,Requerimiento
from .forms import SearchForm, PlanillaForm, PlanillaPersonalForm
from . import constants


class DashboardView(TemplateView):
    template_name = 'pegasus/dashboard.html'


class RequerimientoList(FilteredListView):
    # Normal ListView options
    model = Requerimiento
    paginate_by = 20
    template_name = 'humanresources/requerimiento_list.html'

    # FilteredListView options
    form_class = SearchForm
    search_fields = ['ano_eje']

class OrdenList(FilteredListView):
    # Normal ListView options
    model = Orden
    paginate_by = 20
    template_name = 'humanresources/orden_list.html'

    # FilteredListView options
    form_class = SearchForm
    search_fields = ['ano_eje']

    
    # def get_queryset(self):
    #     queryset = super(OrdenList, self).get_queryset()
    #     return queryset.prefetch_related('estado', )



class PersonalList(FilteredListView):
    # Normal ListView options
    model = Personal
    paginate_by = 15
    template_name = 'humanresources/personal_list.html'

    # FilteredListView options
    form_class = SearchForm
    search_fields = ['dni', 'nomb_comp', ]

    def get_queryset(self):
        queryset = super(PersonalList, self).get_queryset()
        return queryset.prefetch_related('mod_laboral', )


class PlanillaAddView(FilteredListView):
    model = Personal
    paginate_by = 100
    form_class = PlanillaPersonalForm
    template_name = 'humanresources/planilla_add.html'

    # filter_fields = ['mod_laboral', ]

    def form_valid(self, form):
        """Return the queryset when form has been submitted."""
        queryset = super(PlanillaAddView, self).form_valid(form)

        mod_laboral = form.cleaned_data['mod_laboral']
        queryset = queryset.filter(mod_laboral=mod_laboral)

        entidad = form.cleaned_data['entidad']
        queryset = queryset.filter(entidad=entidad)

        return queryset.filter(situacion=constants.SITUACION_ALTA)

    def form_invalid(self, form):
        return Personal.objects.none()


class PlanillaModalAddView(CreateView):
    form = Planilla
    form_class = PlanillaForm
    template_name = 'humanresources/modals/planilla_add.html'


class MarcacionList(FilteredListView):
    # Normal ListView options
    model = Marcacion
    paginate_by = 15
    template_name = 'humanresources/marcacion_list.html'

    # FilteredListView options
    form_class = SearchForm
    search_fields = ['personal__dni', ]

    def get_queryset(self):
        queryset = super(MarcacionList, self).get_queryset()
        if self.request.current_year:
            queryset = queryset.filter(fecha_hora__year=self.request.current_year)
        return queryset.prefetch_related('personal', )


class PlanillaList(FilteredListView):
    # Normal ListView options
    model = Planilla
    paginate_by = 15
    template_name = 'humanresources/planilla_list.html'

    # FilteredListView options
    form_class = SearchForm
    search_fields = ['n_expediente', ]

    def get_queryset(self):
        queryset = super(PlanillaList, self).get_queryset()
        if self.request.current_year:
            queryset = queryset.filter(ano_eje=self.request.current_year)
        return queryset.prefetch_related('mod_laboral', 'tipo_planilla', 'entidad', )


class PersonalEdit(UpdateView):
    model = Personal
    template_name = 'humanresources/personal_add_edit.html'
    fields = ['dni', 'ap_paterno', 'ap_materno']


class PersonalAdd(CreateView):
    model = Personal
    template_name = 'humanresources/personal_add_edit.html'


class PlanillaDetail(DetailView):
    model = Planilla
    template_name = 'humanresources/planilla_detail.html'


class PlanillaTrabDetail(DetailView):
    model = PlanillaTrab
    template_name = 'humanresources/planilla_trab_detail.html'

#class PlanillaTrabDetailEdit(UpdateView):
    #model = PlanillaTrab
    #template_name = 'planilla_trab_detail.html'

src/pegasus/templates/humanresources/marcacion_list.html
{% extends 'pegasus/base.html' %}
{% load bootstrap3 paginator %}

{% block content %}
    <div class="page-header">
        <h3>Marcaciones</h3>
    </div>

    <div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Personal</th>
                <th>Fecha</th>
                <th>Tipo_Hor</th>
                <th>Turno</th>
                <th>Registro</th>
                <th>Tipo</th>
            </tr>
        </thead>
        <tbody>
            {% for marcacion in marcacion_list %}
            <tr>
                <td>
                    <a href="{% url "personal_edit" marcacion.personal.dni %}">
                        {{ marcacion.personal.nomb_comp }}
                    </a>
                </td>
                <td>{{ marcacion.fecha_hora }}</td>
                <td>{{ marcacion.tipo_hor }}</td>
                <td>{{ marcacion.turno }}</td>
                <td>{{ marcacion.registro }}</td>
                <td>{{ marcacion.get_tipo }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    {% paginator %}
{% endblock %}

src/pegasus/templates/humanresources/orden_list.html
{% extends 'pegasus/base.html' %}
{% load paginator %}

{% block content %}

<div class="page-header">
        <div class="pull-right hidden-print">
        

         
   

   <!--  <div class="row-fluid">
      <select class="selectpicker" data-show-subtext="true" data-live-search="true">
        <option data-subtext> 2009 </option>
        <option data-subtext>2010</option>
        <option data-subtext>2011</option>
        <option data-subtext>2012</option>
        <option data-subtext>2013</option>
        <option data-subtext="Rep California" disabled="disabled">2014</option>
      </select>
      
    </div> -->

 


        </div>
        <h3 class="sub-header">Ordenes de Compra / Servicio</h3>
</div>


    

    <div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Ano</th>
                <th>N_orden</th>
                <th>Tipo</th>
                <th>Num_doc</th>
              
            </tr>
        </thead>
        <tbody>
            {% for orden in orden_list %}
            <tr>
                <td>{{ orden.ano_eje }}</td>
                <td>{{ orden.n_orden }}</td>
                <td>{{ orden.tipo }}</td>


                <td>{{ orden.num_doc }}</td>

               
               





            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    {% paginator %}
{% endblock %}

src/pegasus/templates/humanresources/personal_add_edit.html
{% extends 'pegasus/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h5 class="sub-header">
    {% if personal.dni %}
        {{ personal.nomb_comp }}
    {% else %}
        Nuevo personal
    {% endif %}
    </h5>

    {% csrf_token %}

    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Guardar
        </button>
    {% endbuttons %}
{% endblock %}

src/pegasus/templates/humanresources/personal_list.html
{% extends 'pegasus/base.html' %}
{% load paginator %}

{% block content %}

<div class="page-header">
        <div class="pull-right hidden-print">
         <a href="{% url 'personal_add' %}" class="btn btn-hg btn-info"><i class="icon-plus icon-white"></i> Nuevo Personal</a>
        </div>
        <h3 class="sub-header">Personal de Planta</h3>
</div>


    

    <div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Est.</th>
                <th>Cat.</th>
                <th>DNI</th>
                <th>Ap. / Nom.</th>
                <th>Fec. Nac.</th>
                <th>Edad</th>
                <th>Sex</th>
            </tr>
        </thead>
        <tbody>
            {% for personal in personal_list %}
            <tr>
                <td>{{ personal.get_situacion_display }}</td>
                <td>{{ personal.mod_laboral }}</td>
                <td>{{ personal.dni }}</td>
                <td>
                    <a href="{% url 'personal_edit' personal.dni %}">
                        {{ personal.nomb_comp }}
                    </a>
                </td>
                <td>{{ personal.fecha_nac|date }}</td>
                <td>{{ personal.get_years_old }}</td>
                <td>{{ personal.get_sexo_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    {% paginator %}
{% endblock %}

src/pegasus/templates/humanresources/planilla_add.html
{% extends 'pegasus/base.html' %}
{% load bootstrap3 %}

{% block content %}
<form class="form" action='' method="POST">
    {% csrf_token %}
    <div class="page-header">
        <div class="pull-right hidden-print">
            <button type="submit" class="btn-hg btn-success"><i class="icon-plus icon-white"></i> Guardar</button>
        </div>

        <h3>Nueva planilla</h3>
    </div>

    <form class="form" action='' method="GET">
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-default">Filtrar</button>
    </form>

    {% if form.is_valid %}
    <h4>{{ paginator.count }} personas</h4>
    <div class="table-responsive">
    <table class="table table-condensed">
        <thead>
            <tr>
                <th>N°</th>
                <th>Trabajador</th>
                <th>Tipo Plan.</th>
                <th>Remuneración</th>
            </tr>
        </thead>
        <tbody>
            {% for personal in personal_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="">{{ personal }}</a><br/>
                    {{ personal.dni }}
                </td>
                <td>{{ personal.mod_laboral }}</td>
                <td>{{ personal.monto_rem }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
</form>
    {% endif %}
{% endblock %}

src/pegasus/templates/humanresources/planilla_detail.html
{% extends 'pegasus/base.html' %}

{% block content %}
    <h2 class="sub-header">Planilla {{ planilla.n_planilla }}</h2>


    <div class="">
        <dl>
            <dt>Año:</dt>
            <dd>{{ planilla.ano_eje }} </dd>
            <dt>Mes:</dt>
            <dd>{{ planilla.mes }}</dd>
        </dl>
    </div>

    <h3>Personal</h3>
    <div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>N°</th>
                <th>DNI</th>
                <th>Nombre</th>
                <th>Reg. Pensionario</th>
                <th>Nivel</th>
                <th>Remuneración</th>
                <th>DT</th>
                <th>DT</th>
            </tr>
        </thead>
        <tbody>
            {% for planilla_trab in planilla.get_planilla_trabs %}
            <tr>
                <td>{{ forloop.counter }}</td> <!-- sirve para numerar los registros -->
                <td><a href="{% url 'planilla_trab_detail' current_year planilla_trab.id %}">{{ planilla_trab.personal.dni }}</a></td>
                <td>{{ planilla_trab.personal }}</td>
                <td>{{ planilla_trab.reg_pension.abrev }}</td>
                <td>{{ planilla_trab.get_nivel_remunerativo }}</td>
                <td>{{ planilla_trab.monto_rem }}</td>
                <td>{{ planilla_trab.dias_tot }}</td>
                <td>{{ planilla_trab.dias_fer }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

src/pegasus/templates/humanresources/planilla_list.html
{% extends 'pegasus/base.html' %}
{% load paginator %}

{% block content %}
    <div class="page-header">
        <div class="pull-right hidden-print">
            <a href="{% url 'planilla_add' current_year %}" class="btn btn-hg btn-info"><i class="icon-plus icon-white"></i> Nueva planilla</a>
        </div>
        <h3>Planillas {{ current_year }}</h3>
    </div>

<div class="table-responsive">
<table class="table table-striped">
    <thead>
        <tr>
            <th>N° Planilla</th>
            <th>Mod. Lab.</th>
            <th>Tipo Plan.</th>
            <th>Entidad</th>
            <th>Fuente Finac.</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody>
        {% for planilla in planilla_list %}
        <tr>

            <td><a href="{% url 'planilla_detail' current_year planilla.id %}">{{ planilla.n_planilla }}</a>
            </td>

            <td>{{ planilla.mod_laboral }}</td>
            <td>{{ planilla.tipo_planilla }}</td>
            <td>{{ planilla.entidad }}</td>
            <td>{{ planilla.get_fuente_financ }}</td>
            <td>{{ planilla.estado }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% paginator %}

{% endblock %}

src/pegasus/templates/humanresources/planilla_trab_detail.html
{% extends 'pegasus/base.html' %}

{% block content %}
    <h2 class="sub-header">Planilla Trab {{ planillatrab }}</h2>
    {{ planillatrab.personal }}
    <h3>Detalles</h3>
    <div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>N°</th>
                <th>Codigo</th>
                <th>Concepto</th>
                <th>Valor</th>
                <th>%</th>
                <th>Monto</th>
            </tr>
        </thead>
        <tbody>
            {% for planilla_detalle in planillatrab.get_planilla_detalles %}
            <tr>
                <td>{{ planilla_detalle.get_ind_display }}</td>
                <td>{{ planilla_detalle.concepto.codigo }}</td>
                <td>{{ planilla_detalle.concepto }}</td>
                <td>{{ planilla_detalle.valor }}</td>
                <td>{{ planilla_detalle.porcen }}</td>
                <td>{{ planilla_detalle.monto }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

src/pegasus/templates/humanresources/planilla_trab_detail_edit.html
{% extends 'pegasus/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h2 class="sub-header">
    {% if planilla_detalle.id %}
        {{ planilla_detalle.dni }}
    {% else %}
        Nuevo personal
    {% endif %}
    </h2>

    {% csrf_token %}

    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Guardar
        </button>
    {% endbuttons %}
{% endblock %}
